### ISSUE TITLE
Is the datetime format arbitrary? Or, is it a standard of some kind?

### ISSUE THREAD

**Issue by ryanwmoore** [watson-developer-cloud/api-guidelines#5]
From [the README](https://github.com/watson-developer-cloud/api-guidelines/blob/master/README.md):

> Dates returned in responses should be formatted like: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'

I'm no datetime expert. Googling around, I could not verify that it is some sort of standard. Therefore, this seems like an arbitrary formatting decision.
1. Does this format have a proper name? If so, please document its name. This lets developers more easily find code to do the correct formatting.
2. If the format does not have a proper name/standard, please briefly justify the arbitrary choice (e.g., "This format string results in a high-resolution, human-readable date-time.")

**Comment by seh** [comment]
It's one of the [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601#Combined_date_and_time_representations) variants.
Note that ISO 8601 is coy about those fractional seconds (milliseconds). Per [Wikipedia](https://en.wikipedia.org/wiki/ISO_8601#General_principles):

> If necessary for a particular application, the standard supports the addition of a decimal fraction to the smallest time value in the representation.

[Mandating UTC](https://en.wikipedia.org/wiki/ISO_8601#UTC) is odd, though.

**Comment by ryanwmoore** [comment]
ISO 8601 was my assumption but, I wasn't confident enough to make that claim.
